language: python
python:
  - "2.7"
  - "3.6"
  - "3.7"
  - "pypy"
  - "pypy3"
addons:
  apt:
    packages:
      - pandoc
before_install:
  - cd python
install: "pip install -r dev-requirements.txt"
script: nosetests
sudo: false
